### ISSUE TITLE
Race condition creating NetworkService object

### ISSUE THREAD

**Issue by net147** [nemomobile/libconnman-qt#150]
When a NetworkService object is constructed, there is a race condition where property changes may be missed and the NetworkService property cache will not have the proper values.

Sequence:
1. NetworkManager creates a NetworkService object, passing in the initial properties to be used in the NetworkService property cache
2. The NetworkService object constructor connects to the D-Bus object corresponding to it and sets up a connection from PropertyChanged signal on the D-Bus object to the updateProperty slot

Between steps 1 and 2, several properties may have been changed in the underlying service.

**Comment by lpotter** [comment]
Thank you. I have gotten connman-qt added to mer bugs components, and entered it there.

https://bugs.merproject.org/show_bug.cgi?id=1039
